# Generated by Django 2.0.4 on 2018-04-21 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('cover_photo', models.ImageField(upload_to='static/media')),
                ('profile_picture', models.ImageField(upload_to='static/media')),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('MI', models.CharField(max_length=200)),
                ('Sex', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], default=True, max_length=6)),
                ('date_of_birth', models.DateField()),
                ('Age', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
